### ISSUE TITLE
请问plottinglayer类构造中opts配置是否有用？

### ISSUE THREAD

**Issue by TAlcantara** [worlddai/plot_ol#1]
按照源码来看，标绘图层用的是简单地vector图层，且并没有传入任何配置，是否意味着plottinglayer实际上并不支持对图层的详细定制化

**Comment by worlddai** [comment]
是的。这是预留项，目前没有任何作用。plot_ol目前只是实现在地图上面进行封装了一层标绘图层，地图本身的layer定制你需要根据你自己业务需求，往地图上放置layer。

**Comment by TAlcantara** [comment]
> 是的。这是预留项，目前没有任何作用。plot_ol目前只是实现在地图上面进行封装了一层标绘图层，地图本身的layer定制你需要根据你自己业务需求，往地图上放置layer。

明确了，多谢解答
